name: elaugment
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - automat=0.7.0
  - backcall=0.1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - cffi=1.11.5
  - constantly=15.1.0
  - cryptography=2.3
  - cryptography-vectors=2.3
  - entrypoints=0.2.3
  - gmp=6.1.2
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - idna=2.7
  - incremental=17.5.0
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - libsodium=1.0.16
  - markupsafe=1.0
  - mistune=0.8.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.6.0
  - openssl=1.0.2o
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyzmq=17.1.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - simplegeneric=0.8.1
  - terminado=0.8.1
  - testpath=0.3.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - zeromq=4.2.5
  - zope=1.0
  - zope.interface=4.5.0
  - bzip2=1.0.6
  - cloudpickle=0.5.3
  - cycler=0.10.0
  - dask-core=0.18.2
  - dbus=1.13.0
  - decorator=4.3.0
  - expat=2.2.5
  - fontconfig=2.13.0
  - freetype=2.8.1
  - gettext=0.19.8.1
  - glib=2.55.0
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - icu=58.2
  - imageio=2.3.0
  - jpeg=9c
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.34
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=2.2.2
  - ncurses=6.1
  - networkx=2.1
  - olefile=0.45.1
  - pcre=8.41
  - pillow=5.2.0
  - pip=18.0
  - pthread-stubs=0.4
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=0.5.2
  - qt=5.6.2
  - readline=7.0
  - scikit-image=0.14.0
  - setuptools=40.0.0
  - sip=4.18
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - wheel=0.31.1
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - intel-openmp=2018.0.3
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libopenblas=0.2.20
  - libstdcxx-ng=7.2.0
  - mkl=2018.0.3
  - numpy=1.14.3
  - numpy-base=1.14.3
prefix: /home/tim/anaconda3/envs/elaugment
